#movie_recommender function

In [121]:
import numpy as np
import pandas as pd
import os
import zipfile
import ast

In [ ]:
!kaggle datasets download -d tmdb/tmdb-movie-metadata

In [123]:
zip_path = 'tmdb-movie-metadata.zip'
extract_path = '/content/'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [124]:
movies = pd.read_csv('/content/tmdb_5000_movies.csv')

In [125]:
credits=pd.read_csv('/content/tmdb_5000_credits.csv')

In [126]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [127]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [128]:
movies=movies.merge(credits,on='title')

In [129]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [130]:
movies=movies[['id','title','overview','genres','keywords','cast','crew']]

In [131]:
movies.head(2)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [132]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [133]:
movies.shape

(4809, 7)

In [134]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [135]:
movies.duplicated().sum()

np.int64(0)

In [136]:
movies.genres

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4804    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                   []
4808                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4809, dtype: object

In [137]:
a=ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

In [138]:
calculation = '{"id": 28, "name": "Action"}'
result=ast.literal_eval(calculation)


print(result['id'])

28

In [139]:
import ast
def convert(obj):
  l=[]
  for i in ast.literal_eval(obj):
    print(i)
    l.append(i['name'])
  return l

In [140]:
convert('[{"id": 28, "name": "Action"},{"id":23,"name":"adventure"}]')

{'id': 28, 'name': 'Action'}
{'id': 23, 'name': 'adventure'}

['Action', 'adventure']

In [141]:
movies['genres']=movies['genres'].apply(convert)

Streaming output truncated to the last 5000 lines.
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 9648, 'name': 'Mystery'}
{'id': 27, 'name': 'Horror'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 80, 'name': 'Crime'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 9648, 'name': 'Mystery'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 10752, 'name': 'War'}
{'id': 14, 'name': 'Fantasy'}
{'id': 18, 'name': 'Drama'}
{'id': 27, 'name': 'Horror'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 53, 'name': 'Thriller'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 12, 'name': 'Adventure'}
{'id': 16, 'name': 'Animation'}
{'id': 35, 'name': 'Comedy'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 10751, 'name': 'Family'}
{'id': 10402, 'name': 'Music'}
{'id': 99, 'name': 'Documentary'}
{'id': 28, 'name': 'Action'}
{'id': 14, 'name': 'Fantasy'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 10402, 'name': 'Music'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 53, 'name': 'Thriller'}
{'id': 28, 'name': 'Action'}
{'id': 35, 'name': 'Comedy'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 14, 'name': 'Fantasy'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10402, 'name': 'Music'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 10751, 'name': 'Family'}
{'id': 28, 'name': 'Action'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 10402, 'name': 'Music'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 28, 'name': 'Action'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 14, 'name': 'Fantasy'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 10751, 'name': 'Family'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 10402, 'name': 'Music'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 53, 'name': 'Thriller'}
{'id': 12, 'name': 'Adventure'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 9648, 'name': 'Mystery'}
{'id': 37, 'name': 'Western'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 28, 'name': 'Action'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 9648, 'name': 'Mystery'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 9648, 'name': 'Mystery'}
{'id': 18, 'name': 'Drama'}
{'id': 14, 'name': 'Fantasy'}
{'id': 27, 'name': 'Horror'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 9648, 'name': 'Mystery'}
{'id': 12, 'name': 'Adventure'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 28, 'name': 'Action'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 10752, 'name': 'War'}
{'id': 80, 'name': 'Crime'}
{'id': 53, 'name': 'Thriller'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 9648, 'name': 'Mystery'}
{'id': 12, 'name': 'Adventure'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 12, 'name': 'Adventure'}
{'id': 28, 'name': 'Action'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 9648, 'name': 'Mystery'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 53, 'name': 'Thriller'}
{'id': 27, 'name': 'Horror'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 28, 'name': 'Action'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 14, 'name': 'Fantasy'}
{'id': 10402, 'name': 'Music'}
{'id': 18, 'name': 'Drama'}
{'id': 14, 'name': 'Fantasy'}
{'id': 16, 'name': 'Animation'}
{'id': 12, 'name': 'Adventure'}
{'id': 10751, 'name': 'Family'}
{'id': 53, 'name': 'Thriller'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 14, 'name': 'Fantasy'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 10769, 'name': 'Foreign'}
{'id': 10749, 'name': 'Romance'}
{'id': 14, 'name': 'Fantasy'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10402, 'name': 'Music'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 10752, 'name': 'War'}
{'id': 18, 'name': 'Drama'}
{'id': 37, 'name': 'Western'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 53, 'name': 'Thriller'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 53, 'name': 'Thriller'}
{'id': 9648, 'name': 'Mystery'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 10752, 'name': 'War'}
{'id': 35, 'name': 'Comedy'}
{'id': 9648, 'name': 'Mystery'}
{'id': 27, 'name': 'Horror'}
{'id': 18, 'name': 'Drama'}
{'id': 10402, 'name': 'Music'}
{'id': 12, 'name': 'Adventure'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 18, 'name': 'Drama'}
{'id': 10751, 'name': 'Family'}
{'id': 35, 'name': 'Comedy'}
{'id': 10751, 'name': 'Family'}
{'id': 36, 'name': 'History'}
{'id': 18, 'name': 'Drama'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 16, 'name': 'Animation'}
{'id': 35, 'name': 'Comedy'}
{'id': 10751, 'name': 'Family'}
{'id': 14, 'name': 'Fantasy'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 27, 'name': 'Horror'}
{'id': 10749, 'name': 'Romance'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 14, 'name': 'Fantasy'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 53, 'name': 'Thriller'}
{'id': 9648, 'name': 'Mystery'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10752, 'name': 'War'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 10402, 'name': 'Music'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 27, 'name': 'Horror'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 36, 'name': 'History'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 9648, 'name': 'Mystery'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 28, 'name': 'Action'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 27, 'name': 'Horror'}
{'id': 9648, 'name': 'Mystery'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 36, 'name': 'History'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 36, 'name': 'History'}
{'id': 28, 'name': 'Action'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 27, 'name': 'Horror'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 9648, 'name': 'Mystery'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 10752, 'name': 'War'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10752, 'name': 'War'}
{'id': 28, 'name': 'Action'}
{'id': 35, 'name': 'Comedy'}
{'id': 53, 'name': 'Thriller'}
{'id': 99, 'name': 'Documentary'}
{'id': 10402, 'name': 'Music'}
{'id': 10751, 'name': 'Family'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 10751, 'name': 'Family'}
{'id': 10749, 'name': 'Romance'}
{'id': 10402, 'name': 'Music'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 18, 'name': 'Drama'}
{'id': 37, 'name': 'Western'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 10751, 'name': 'Family'}
{'id': 35, 'name': 'Comedy'}
{'id': 27, 'name': 'Horror'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 10751, 'name': 'Family'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 35, 'name': 'Comedy'}
{'id': 10751, 'name': 'Family'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10751, 'name': 'Family'}
{'id': 18, 'name': 'Drama'}
{'id': 27, 'name': 'Horror'}
{'id': 80, 'name': 'Crime'}
{'id': 53, 'name': 'Thriller'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 14, 'name': 'Fantasy'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 10751, 'name': 'Family'}
{'id': 12, 'name': 'Adventure'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 18, 'name': 'Drama'}
{'id': 10752, 'name': 'War'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 10402, 'name': 'Music'}
{'id': 18, 'name': 'Drama'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 9648, 'name': 'Mystery'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 28, 'name': 'Action'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 28, 'name': 'Action'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 37, 'name': 'Western'}
{'id': 53, 'name': 'Thriller'}
{'id': 27, 'name': 'Horror'}
{'id': 28, 'name': 'Action'}
{'id': 35, 'name': 'Comedy'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 10752, 'name': 'War'}
{'id': 80, 'name': 'Crime'}
{'id': 53, 'name': 'Thriller'}
{'id': 36, 'name': 'History'}
{'id': 18, 'name': 'Drama'}
{'id': 10752, 'name': 'War'}
{'id': 28, 'name': 'Action'}
{'id': 10751, 'name': 'Family'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 12, 'name': 'Adventure'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 10749, 'name': 'Romance'}
{'id': 10749, 'name': 'Romance'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 9648, 'name': 'Mystery'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 14, 'name': 'Fantasy'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 27, 'name': 'Horror'}
{'id': 9648, 'name': 'Mystery'}
{'id': 53, 'name': 'Thriller'}
{'id': 12, 'name': 'Adventure'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 10752, 'name': 'War'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 10402, 'name': 'Music'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 28, 'name': 'Action'}
{'id': 35, 'name': 'Comedy'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 16, 'name': 'Animation'}
{'id': 12, 'name': 'Adventure'}
{'id': 10751, 'name': 'Family'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 10752, 'name': 'War'}
{'id': 18, 'name': 'Drama'}
{'id': 10751, 'name': 'Family'}
{'id': 18, 'name': 'Drama'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 16, 'name': 'Animation'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10751, 'name': 'Family'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 9648, 'name': 'Mystery'}
{'id': 53, 'name': 'Thriller'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 53, 'name': 'Thriller'}
{'id': 28, 'name': 'Action'}
{'id': 53, 'name': 'Thriller'}
{'id': 10752, 'name': 'War'}
{'id': 10402, 'name': 'Music'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 80, 'name': 'Crime'}
{'id': 16, 'name': 'Animation'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 12, 'name': 'Adventure'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 18, 'name': 'Drama'}
{'id': 53, 'name': 'Thriller'}
{'id': 10402, 'name': 'Music'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 10751, 'name': 'Family'}
{'id': 14, 'name': 'Fantasy'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 28, 'name': 'Action'}
{'id': 12, 'name': 'Adventure'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10751, 'name': 'Family'}
{'id': 10402, 'name': 'Music'}
{'id': 10749, 'name': 'Romance'}
{'id': 35, 'name': 'Comedy'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 10752, 'name': 'War'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 27, 'name': 'Horror'}
{'id': 878, 'name': 'Science Fiction'}
{'id': 53, 'name': 'Thriller'}
{'id': 18, 'name': 'Drama'}
{'id': 27, 'name': 'Horror'}
{'id': 53, 'name': 'Thriller'}
{'id': 35, 'name': 'Comedy'}
{'id': 10751, 'name': 'Family'}
{'id': 35, 'name': 'Comedy'}
{'id': 35, 'name': 'Comedy'}
{'id': 10751, 'name': 'Family'}
{'id': 14, 'name': 'Fantasy'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}
{'id': 99, 'name': 'Documentary'}
{'id': 10402, 'name': 'Music'}
{'id': 10749, 'name': 'Romance'}
{'id': 18, 'name': 'Drama'}
{'id': 18, 'name': 'Drama'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 35, 'name': 'Comedy'}
{'id': 27, 'name': 'Horror'}

In [142]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4809, dtype: object

In [143]:
movies['keywords']

0       [{"id": 1463, "name": "culture clash"}, {"id":...
1       [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2       [{"id": 470, "name": "spy"}, {"id": 818, "name...
3       [{"id": 849, "name": "dc comics"}, {"id": 853,...
4       [{"id": 818, "name": "based on novel"}, {"id":...
                              ...
4804    [{"id": 5616, "name": "united states\u2013mexi...
4805                                                   []
4806    [{"id": 248, "name": "date"}, {"id": 699, "nam...
4807                                                   []
4808    [{"id": 1523, "name": "obsession"}, {"id": 224...
Name: keywords, Length: 4809, dtype: object

In [144]:
movies['keywords']=movies['keywords'].apply(convert)

Streaming output truncated to the last 5000 lines.
{'id': 2987, 'name': 'gang war'}
{'id': 10683, 'name': 'coming of age'}
{'id': 187056, 'name': 'woman director'}
{'id': 208289, 'name': '1980s'}
{'id': 572, 'name': 'sex'}
{'id': 1361, 'name': 'salesclerk'}
{'id': 3015, 'name': 'fast food restaurant'}
{'id': 3925, 'name': 'boredom'}
{'id': 5625, 'name': 'relationship problems'}
{'id': 8508, 'name': 'party'}
{'id': 14534, 'name': 'relationship'}
{'id': 14964, 'name': 'drug'}
{'id': 15237, 'name': 'alcohol abuse'}
{'id': 15479, 'name': 'fashion'}
{'id': 155939, 'name': 'group of friends'}
{'id': 894, 'name': 'depression'}
{'id': 5565, 'name': 'biography'}
{'id': 14964, 'name': 'drug'}
{'id': 549, 'name': 'prostitute'}
{'id': 657, 'name': 'fire'}
{'id': 918, 'name': 'newspaper'}
{'id': 10183, 'name': 'independent film'}
{'id': 187056, 'name': 'woman director'}
{'id': 494, 'name': 'father son relationship'}
{'id': 509, 'name': 'denmark'}
{'id': 2251, 'name': 'lie'}
{'id': 2337, 'name': 'pedophilia'}
{'id': 4590, 'name': 'kindergarten'}
{'id': 5905, 'name': 'father'}
{'id': 7946, 'name': 'deer'}
{'id': 10103, 'name': 'children'}
{'id': 10508, 'name': 'teacher'}
{'id': 10873, 'name': 'school'}
{'id': 14576, 'name': 'pedophile'}
{'id': 15160, 'name': 'divorce'}
{'id': 33688, 'name': 'hunting'}
{'id': 65, 'name': 'holiday'}
{'id': 5609, 'name': 'nostalgia'}
{'id': 11336, 'name': 'young boy'}
{'id': 170472, 'name': 'bb gun'}
{'id': 170487, 'name': 'essay'}
{'id': 170496, 'name': 'christmas tree dealer'}
{'id': 170499, 'name': 'mall santa'}
{'id': 207317, 'name': 'christmas'}
{'id': 207883, 'name': '1940s'}
{'id': 828, 'name': 'waitress'}
{'id': 966, 'name': 'beach'}
{'id': 10183, 'name': 'independent film'}
{'id': 13042, 'name': 'soccer'}
{'id': 14659, 'name': 'girl'}
{'id': 177973, 'name': 'chance meeting'}
{'id': 187844, 'name': 'flashback'}
{'id': 279, 'name': 'usa'}
{'id': 293, 'name': 'female nudity'}
{'id': 703, 'name': 'detective'}
{'id': 2176, 'name': 'music teacher'}
{'id': 2483, 'name': 'nudity'}
{'id': 4470, 'name': 'punk'}
{'id': 6270, 'name': 'high school'}
{'id': 7002, 'name': 'vigilante'}
{'id': 7920, 'name': 'violence in schools'}
{'id': 9826, 'name': 'murder'}
{'id': 10183, 'name': 'independent film'}
{'id': 10508, 'name': 'teacher'}
{'id': 10726, 'name': 'gang'}
{'id': 10768, 'name': 'lesbian'}
{'id': 12365, 'name': 'gang rape'}
{'id': 14857, 'name': 'juvenile delinquent'}
{'id': 173919, 'name': 'punk band'}
{'id': 206850, 'name': 'canuxploitation'}
{'id': 622, 'name': 'bet'}
{'id': 15160, 'name': 'divorce'}
{'id': 34214, 'name': 'gender'}
{'id': 163096, 'name': 'battle of the sexes'}
{'id': 208450, 'name': 'life competition'}
{'id': 14794, 'name': 'lust'}
{'id': 160780, 'name': 'love crime'}
{'id': 90, 'name': 'paris'}
{'id': 1952, 'name': 'socially deprived family'}
{'id': 2132, 'name': 'literature'}
{'id': 2173, 'name': 'illegal immigration'}
{'id': 2356, 'name': 'immigrant'}
{'id': 2470, 'name': 'education'}
{'id': 3925, 'name': 'boredom'}
{'id': 4034, 'name': 'class society'}
{'id': 7920, 'name': 'violence in schools'}
{'id': 8746, 'name': 'republicanism'}
{'id': 8747, 'name': 'diversity'}
{'id': 10508, 'name': 'teacher'}
{'id': 10873, 'name': 'school'}
{'id': 190116, 'name': 'school life'}
{'id': 193547, 'name': 'teachers and students'}
{'id': 8685, 'name': 'anti-christ'}
{'id': 18401, 'name': 'contemporary setting'}
{'id': 41600, 'name': 'laundry'}
{'id': 156174, 'name': 'occult'}
{'id': 161261, 'name': 'demonic possession'}
{'id': 163055, 'name': 'satanic cult'}
{'id': 172376, 'name': 'lucky charm'}
{'id': 172382, 'name': 'woman in jeopardy'}
{'id': 172383, 'name': 'eating disorder'}
{'id': 172391, 'name': 'catholic priest'}
{'id': 75, 'name': 'gunslinger'}
{'id': 797, 'name': 'showdown'}
{'id': 3739, 'name': 'funeral'}
{'id': 3754, 'name': 'legend'}
{'id': 4277, 'name': 'to shoot dead'}
{'id': 9503, 'name': 'outlaw'}
{'id': 10909, 'name': 'lawyer'}
{'id': 13132, 'name': 'pistol'}
{'id': 14574, 'name': 'rancher'}
{'id': 33600, 'name': 'stagecoach'}
{'id': 155291, 'name': 'cowboy'}
{'id': 170173, 'name': "children's book"}
{'id': 181318, 'name': "asperger's syndrome"}
{'id': 181319, 'name': 'electrical engineer'}
{'id': 192134, 'name': "asperger's"}
{'id': 30, 'name': 'individual'}
{'id': 242, 'name': 'new york'}
{'id': 704, 'name': 'adolescence'}
{'id': 2148, 'name': 'colombia'}
{'id': 2149, 'name': 'drug traffic'}
{'id': 2150, 'name': 'cocaine'}
{'id': 2151, 'name': 'drug crime'}
{'id': 2173, 'name': 'illegal immigration'}
{'id': 2174, 'name': 'maquiladora'}
{'id': 3800, 'name': 'airplane'}
{'id': 3930, 'name': 'bravery'}
{'id': 10508, 'name': 'teacher'}
{'id': 13149, 'name': 'pregnancy'}
{'id': 155023, 'name': 'self esteem'}
{'id': 237, 'name': 'gay'}
{'id': 936, 'name': 'loss of mother'}
{'id': 1328, 'name': 'secret'}
{'id': 1862, 'name': 'coming out'}
{'id': 1872, 'name': 'loss of father'}
{'id': 10163, 'name': 'cancer'}
{'id': 208390, 'name': 'lgbt elderly'}
{'id': 1299, 'name': 'monster'}
{'id': 5319, 'name': 'pub'}
{'id': 179431, 'name': 'duringcreditsstinger'}
{'id': 572, 'name': 'sex'}
{'id': 2483, 'name': 'nudity'}
{'id': 3616, 'name': 'college'}
{'id': 157632, 'name': 'fraternity'}
{'id': 158507, 'name': 'gross out comedy'}
{'id': 160450, 'name': 'dean'}
{'id': 171400, 'name': 'fraternity house'}
{'id': 208983, 'name': 'probation'}
{'id': 208992, 'name': '1960s'}
{'id': 209506, 'name': 'college freshman'}
{'id': 236316, 'name': 'anarchic comedy'}
{'id': 3271, 'name': 'secret organization'}
{'id': 3272, 'name': 'secret intelligence service'}
{'id': 3275, 'name': 'nuclear radiation'}
{'id': 3286, 'name': 'fort knox'}
{'id': 3287, 'name': 'aston martin'}
{'id': 3288, 'name': 'secret lab'}
{'id': 3291, 'name': 'kentucky'}
{'id': 3293, 'name': 'gas attack'}
{'id': 3800, 'name': 'airplane'}
{'id': 156095, 'name': 'british secret service'}
{'id': 179431, 'name': 'duringcreditsstinger'}
{'id': 4958, 'name': 'injection'}
{'id': 6562, 'name': 'celebrity'}
{'id': 8201, 'name': 'satire'}
{'id': 40847, 'name': 'near future'}
{'id': 158276, 'name': 'metamorphosis'}
{'id': 178657, 'name': 'tech noir'}
{'id': 188957, 'name': 'virus'}
{'id': 191564, 'name': 'body horror'}
{'id': 65, 'name': 'holiday'}
{'id': 290, 'name': 'angel'}
{'id': 818, 'name': 'based on novel'}
{'id': 974, 'name': 'bank'}
{'id': 1252, 'name': 'suicide attempt'}
{'id': 1415, 'name': 'small town'}
{'id': 5570, 'name': 'christmas tree'}
{'id': 5571, 'name': 'great depression'}
{'id': 33965, 'name': 'christmas eve'}
{'id': 156115, 'name': 'feel-good ending'}
{'id': 184559, 'name': 'guardian angel'}
{'id': 207317, 'name': 'christmas'}
{'id': 212, 'name': 'london england'}
{'id': 567, 'name': 'alcohol'}
{'id': 572, 'name': 'sex'}
{'id': 818, 'name': 'based on novel'}
{'id': 1803, 'name': 'drug addiction'}
{'id': 2231, 'name': 'drug dealer'}
{'id': 2334, 'name': 'nightclub'}
{'id': 2375, 'name': 'junkie'}
{'id': 2671, 'name': 'heroin'}
{'id': 2694, 'name': 'cold turkey'}
{'id': 3131, 'name': 'modern society'}
{'id': 3298, 'name': 'hallucination'}
{'id': 6054, 'name': 'friendship'}
{'id': 9887, 'name': 'surrealism'}
{'id': 10123, 'name': 'dark comedy'}
{'id': 10261, 'name': 'stealing'}
{'id': 11635, 'name': 'monologue'}
{'id': 34117, 'name': 'cult film'}
{'id': 155936, 'name': 'recovering drug addict'}
{'id': 156117, 'name': 'illegal drugs'}
{'id': 168179, 'name': 'drug deal'}
{'id': 180431, 'name': 'drug rehabilitation'}
{'id': 206829, 'name': 'drug culture'}
{'id': 230607, 'name': 'antihero'}
{'id': 10112, 'name': 'ouija board'}
{'id': 10224, 'name': 'haunting'}
{'id': 161261, 'name': 'demonic possession'}
{'id': 163053, 'name': 'found footage'}
{'id': 179431, 'name': 'duringcreditsstinger'}
{'id': 3864, 'name': 'false identity'}
{'id': 4214, 'name': 'beguilement'}
{'id': 4258, 'name': 'lottery'}
{'id': 5331, 'name': 'village'}
{'id': 8739, 'name': 'jackpot'}
{'id': 10183, 'name': 'independent film'}
{'id': 14985, 'name': 'ireland'}
{'id': 279, 'name': 'usa'}
{'id': 1329, 'name': 'canada'}
{'id': 1419, 'name': 'gun'}
{'id': 1849, 'name': 'homicide'}
{'id': 4277, 'name': 'to shoot dead'}
{'id': 5037, 'name': 'checks and balances'}
{'id': 7548, 'name': 'columbine'}
{'id': 11068, 'name': 'oklahoma city bombing'}
{'id': 163656, 'name': 'gun violence'}
{'id': 187554, 'name': 'person running amok'}
{'id': 2692, 'name': 'arranged marriage'}
{'id': 181962, 'name': 'labor camp'}
{'id': 237, 'name': 'gay'}
{'id': 246, 'name': 'dancing'}
{'id': 657, 'name': 'fire'}
{'id': 2913, 'name': 'diary'}
{'id': 3030, 'name': 'nightmare'}
{'id': 3358, 'name': 'haunted house'}
{'id': 4375, 'name': 'transformation'}
{'id': 6152, 'name': 'supernatural'}
{'id': 6270, 'name': 'high school'}
{'id': 8508, 'name': 'party'}
{'id': 9712, 'name': 'possession'}
{'id': 10170, 'name': 'premonition'}
{'id': 10985, 'name': 'spontaneous combustion'}
{'id': 158713, 'name': 'bdsm'}
{'id': 166287, 'name': 'school bus'}
{'id': 170383, 'name': 'disfigurement'}
{'id': 179878, 'name': 'sleepwalking'}
{'id': 225209, 'name': 'dreams'}
{'id': 5091, 'name': 'kiss'}
{'id': 5832, 'name': 'bed and breakfast place'}
{'id': 8032, 'name': 'florence'}
{'id': 4565, 'name': 'dystopia'}
{'id': 7246, 'name': 'barricade'}
{'id': 14903, 'name': 'home invasion'}
{'id': 221957, 'name': 'constitutional convention'}
{'id': 221958, 'name': 'legalized murder'}
{'id': 221960, 'name': 'social allegory'}
{'id': 793, 'name': 'drowning'}
{'id': 904, 'name': 'pennsylvania'}
{'id': 1468, 'name': 'child murderer'}
{'id': 9775, 'name': 'car set on fire'}
{'id': 9826, 'name': 'murder'}
{'id': 11464, 'name': 'bag over head'}
{'id': 14546, 'name': 'massacre'}
{'id': 14755, 'name': 'power outage'}
{'id': 15292, 'name': 'hanged man'}
{'id': 15365, 'name': 'held captive'}
{'id': 33407, 'name': 'hanging'}
{'id': 34079, 'name': 'death'}
{'id': 155619, 'name': 'attic'}
{'id': 158111, 'name': 'no opening credits'}
{'id': 160329, 'name': 'super-8'}
{'id': 172992, 'name': 'ghost child'}
{'id': 182022, 'name': 'filmed killing'}
{'id': 185767, 'name': 'crime novelist'}
{'id': 1850, 'name': 'daily life'}
{'id': 3692, 'name': 'scandal'}
{'id': 9825, 'name': 'growing up'}
{'id': 15160, 'name': 'divorce'}
{'id': 30, 'name': 'individual'}
{'id': 236, 'name': 'suicide'}
{'id': 531, 'name': 'southern usa'}
{'id': 596, 'name': 'adultery'}
{'id': 787, 'name': 'mississippi'}
{'id': 894, 'name': 'depression'}
{'id': 931, 'name': 'jealousy'}
{'id': 1157, 'name': 'wife husband relationship'}
{'id': 3737, 'name': 'dying and death'}
{'id': 33457, 'name': 'alcoholic'}
{'id': 1852, 'name': 'mutant'}
{'id': 4565, 'name': 'dystopia'}
{'id': 5385, 'name': 'survivor'}
{'id': 14626, 'name': 'astronaut'}
{'id': 14759, 'name': 'ape'}
{'id': 156810, 'name': 'science'}
{'id': 157963, 'name': 'worship'}
{'id': 3199, 'name': 'clown'}
{'id': 158386, 'name': 'golden retriever'}
{'id': 158387, 'name': 'dog actor'}
{'id': 1262, 'name': 'mountains'}
{'id': 2802, 'name': 'mountain village'}
{'id': 6054, 'name': 'friendship'}
{'id': 10988, 'name': 'based on tv series'}
{'id': 11336, 'name': 'young boy'}
{'id': 11451, 'name': 'pokémon'}
{'id': 12392, 'name': 'best friend'}
{'id': 14955, 'name': 'fighting'}
{'id': 41645, 'name': 'based on video game'}
{'id': 201952, 'name': 'pikachu'}
{'id': 210024, 'name': 'anime'}
{'id': 952, 'name': 'lightning'}
{'id': 1227, 'name': 'cemetery'}
{'id': 2546, 'name': 'mask'}
{'id': 12339, 'name': 'slasher'}
{'id': 179422, 'name': 'jason vorhees'}
{'id': 233, 'name': 'japan'}
{'id': 836, 'name': 'resistance'}
{'id': 907, 'name': 'japanese'}
{'id': 1261, 'name': 'river'}
{'id': 1968, 'name': 'prisoners of war'}
{'id': 3434, 'name': 'thailand'}
{'id': 3450, 'name': 'bridge'}
{'id': 3776, 'name': 'officer'}
{'id': 9951, 'name': 'alien'}
{'id': 10539, 'name': 'martian'}
{'id': 12541, 'name': 'misunderstanding'}
{'id': 177349, 'name': 'greedy developer'}
{'id': 663, 'name': 'fortune teller'}
{'id': 1930, 'name': 'kidnapping'}
{'id': 3864, 'name': 'false identity'}
{'id': 161506, 'name': 'heir'}
{'id': 180824, 'name': 'spiritualist'}
{'id': 242, 'name': 'new york'}
{'id': 613, 'name': "new year's eve"}
{'id': 725, 'name': 'lovesickness'}
{'id': 965, 'name': 'age difference'}
{'id': 1252, 'name': 'suicide attempt'}
{'id': 1438, 'name': 'office'}
{'id': 1439, 'name': 'flat'}
{'id': 1440, 'name': 'spaghetti'}
{'id': 1441, 'name': 'christmas party'}
{'id': 1442, 'name': 'winter'}
{'id': 1443, 'name': 'clerk'}
{'id': 1487, 'name': 'tennis racket'}
{'id': 9799, 'name': 'romantic comedy'}
{'id': 34094, 'name': 'extramarital affair'}
{'id': 255, 'name': 'male nudity'}
{'id': 293, 'name': 'female nudity'}
{'id': 828, 'name': 'waitress'}
{'id': 1890, 'name': 'camping'}
{'id': 2483, 'name': 'nudity'}
{'id': 6259, 'name': 'psychopath'}
{'id': 9663, 'name': 'sequel'}
{'id': 9826, 'name': 'murder'}
{'id': 10183, 'name': 'independent film'}
{'id': 10714, 'name': 'serial killer'}
{'id': 10738, 'name': 'diner'}
{'id': 12339, 'name': 'slasher'}
{'id': 14676, 'name': 'series of murders'}
{'id': 14819, 'name': 'violence'}
{'id': 158190, 'name': 'hockey mask'}
{'id': 179422, 'name': 'jason vorhees'}
{'id': 183953, 'name': 'madman'}
{'id': 2106, 'name': 'cold war'}
{'id': 156026, 'name': 'east germany'}
{'id': 577, 'name': 'black people'}
{'id': 898, 'name': 'hip-hop'}
{'id': 1515, 'name': 'block party'}
{'id': 1516, 'name': 'megaphone'}
{'id': 1517, 'name': 'classroom'}
{'id': 1673, 'name': 'brass band'}
{'id': 1674, 'name': 'stage'}
{'id': 657, 'name': 'fire'}
{'id': 801, 'name': 'bounty hunter'}
{'id': 1366, 'name': 'shotgun'}
{'id': 2284, 'name': 'horseback riding'}
{'id': 2673, 'name': 'horse'}
{'id': 3623, 'name': 'cabin'}
{'id': 9454, 'name': 'frontier'}
{'id': 9503, 'name': 'outlaw'}
{'id': 9897, 'name': 'rifle'}
{'id': 10048, 'name': 'unrequited love'}
{'id': 10201, 'name': 'death of father'}
{'id': 10322, 'name': 'native american'}
{'id': 10950, 'name': 'shootout'}
{'id': 11112, 'name': 'search'}
{'id': 13132, 'name': 'pistol'}
{'id': 14540, 'name': 'death by accident'}
{'id': 14819, 'name': 'violence'}
{'id': 14985, 'name': 'ireland'}
{'id': 15111, 'name': 'drinking'}
{'id': 15290, 'name': 'pursuit'}
{'id': 157471, 'name': 'shot through a wall'}
{'id': 158145, 'name': 'flaming arrow'}
{'id': 160840, 'name': 'dream sequence'}
{'id': 187844, 'name': 'flashback'}
{'id': 222133, 'name': 'shot in the heart'}
{'id': 179431, 'name': 'duringcreditsstinger'}
{'id': 178870, 'name': 'evangelist'}
{'id': 186353, 'name': 'revivalism'}
{'id': 934, 'name': 'judge'}
{'id': 1631, 'name': 'concentration camp'}
{'id': 1956, 'name': 'world war ii'}
{'id': 2652, 'name': 'nazis'}
{'id': 3012, 'name': 'court case'}
{'id': 3061, 'name': 'national socialism'}
{'id': 3068, 'name': 'national socialist party'}
{'id': 4172, 'name': 'nuremberg trials'}
{'id': 6145, 'name': 'right and justice'}
{'id': 11038, 'name': 'trial'}
{'id': 6270, 'name': 'high school'}
{'id': 10266, 'name': 'prom'}
{'id': 1556, 'name': 'texas'}
{'id': 3851, 'name': 'dangerous'}
{'id': 7658, 'name': 'kansas'}
{'id': 9656, 'name': 'cattle drive'}
{'id': 9748, 'name': 'revenge'}
{'id': 15225, 'name': 'cattle'}
{'id': 185927, 'name': 'adopted child'}
{'id': 208505, 'name': 'cattle empire'}
{'id': 187056, 'name': 'woman director'}
{'id': 612, 'name': 'hotel'}
{'id': 822, 'name': 'airport'}
{'id': 922, 'name': 'hotel room'}
{'id': 1200, 'name': 'greece'}
{'id': 1566, 'name': 'dream'}
{'id': 8011, 'name': 'greek'}
{'id': 9713, 'name': 'friends'}
{'id': 10818, 'name': 'author'}
{'id': 13028, 'name': 'writer'}
{'id': 14714, 'name': 'summer vacation'}
{'id': 15016, 'name': 'twins'}
{'id': 12564, 'name': 'werewolf'}
{'id': 13130, 'name': 'teenager'}
{'id': 7939, 'name': 'portal'}
{'id': 12434, 'name': 'undertaker'}
{'id': 156075, 'name': 'evil'}
{'id': 162333, 'name': 'tall man'}
{'id': 162334, 'name': 'sentinals'}
{'id': 10183, 'name': 'independent film'}
{'id': 10183, 'name': 'independent film'}
{'id': 187056, 'name': 'woman director'}
{'id': 2628, 'name': 'site of pilgrimage'}
{'id': 4129, 'name': 'widow'}
{'id': 4471, 'name': 'varanasi'}
{'id': 6194, 'name': 'hinduism'}
{'id': 7925, 'name': 'child bride'}
{'id': 7926, 'name': 'mahatma gandhi'}
{'id': 187056, 'name': 'woman director'}
{'id': 187, 'name': 'islam'}
{'id': 458, 'name': 'hippie'}
{'id': 494, 'name': 'father son relationship'}
{'id': 789, 'name': 'muslim'}
{'id': 931, 'name': 'jealousy'}
{'id': 941, 'name': 'tradition'}
{'id': 1463, 'name': 'culture clash'}
{'id': 1536, 'name': 'religious education'}
{'id': 3131, 'name': 'modern society'}
{'id': 5471, 'name': 'pakistani'}
{'id': 5600, 'name': 'daughter'}
{'id': 6150, 'name': 'faith'}
{'id': 6713, 'name': 'integration'}
{'id': 10428, 'name': 'cultural difference'}
{'id': 10183, 'name': 'independent film'}
{'id': 10738, 'name': 'diner'}
{'id': 13043, 'name': 'dating'}
{'id': 33451, 'name': 'masturbation'}
{'id': 496, 'name': 'poetry'}
{'id': 1664, 'name': 'eroticism'}
{'id': 187056, 'name': 'woman director'}
{'id': 236, 'name': 'suicide'}
{'id': 242, 'name': 'new york'}
{'id': 1326, 'name': 'infidelity'}
{'id': 10163, 'name': 'cancer'}
{'id': 10183, 'name': 'independent film'}
{'id': 10226, 'name': 'neighbor'}
{'id': 33632, 'name': 'apartment'}
{'id': 187056, 'name': 'woman director'}
{'id': 715, 'name': 'chocolate'}
{'id': 730, 'name': 'factory worker'}
{'id': 818, 'name': 'based on novel'}
{'id': 985, 'name': 'candy'}
{'id': 986, 'name': 'tv addicted person'}
{'id': 987, 'name': 'overweight child'}
{'id': 1158, 'name': 'grandfather grandson relationship'}
{'id': 1382, 'name': 'factory'}
{'id': 4344, 'name': 'musical'}
{'id': 9457, 'name': 'single'}
{'id': 10508, 'name': 'teacher'}
{'id': 12654, 'name': 'armageddon'}
{'id': 157667, 'name': 'warlock'}
{'id': 534, 'name': 'mexico'}
{'id': 6876, 'name': 'vacation'}
{'id': 9826, 'name': 'murder'}
{'id': 33709, 'name': 'head'}
{'id': 128, 'name': 'love triangle'}
{'id': 520, 'name': 'chicago'}
{'id': 1157, 'name': 'wife husband relationship'}
{'id': 1556, 'name': 'texas'}
{'id': 4511, 'name': 'field'}
{'id': 4932, 'name': 'farm'}
{'id': 6038, 'name': 'marriage'}
{'id': 9673, 'name': 'love'}
{'id': 12987, 'name': 'poverty'}
{'id': 14514, 'name': 'class differences'}
{'id': 154846, 'name': 'farmer'}
{'id': 178977, 'name': 'jealous husband'}
{'id': 188987, 'name': 'boyfriend girlfriend relationship'}
{'id': 190061, 'name': 'harvest'}
{'id': 10183, 'name': 'independent film'}
{'id': 187056, 'name': 'woman director'}
{'id': 718, 'name': 'confession'}
{'id': 931, 'name': 'jealousy'}
{'id': 3030, 'name': 'nightmare'}
{'id': 3734, 'name': 'ambition'}
{'id': 4044, 'name': 'groupie'}
{'id': 6270, 'name': 'high school'}
{'id': 7289, 'name': 'cafeteria'}
{'id': 9748, 'name': 'revenge'}
{'id': 10266, 'name': 'prom'}
{'id': 10877, 'name': 'dead body'}
{'id': 13043, 'name': 'dating'}
{'id': 15479, 'name': 'fashion'}
{'id': 18001, 'name': 'rock band'}
{'id': 18020, 'name': 'fantasy sequence'}
{'id': 18512, 'name': 'slow motion'}
{'id': 33507, 'name': 'multiple identities'}
{'id': 33922, 'name': 'pop music'}
{'id': 34130, 'name': 'makeover'}
{'id': 162875, 'name': 'polaroid camera'}
{'id': 170418, 'name': 'public humiliation'}
{'id': 171556, 'name': 'social outcast'}
{'id': 188947, 'name': 'sidekick'}
{'id': 196645, 'name': 'prank gone wrong'}
{'id': 197077, 'name': 'cliques'}
{'id': 197092, 'name': 'social climbing'}
{'id': 197094, 'name': 'back stabbing'}
{'id': 197106, 'name': 'dead teenager'}
{'id': 197107, 'name': 'goth girls'}
{'id': 242, 'name': 'new york'}
{'id': 572, 'name': 'sex'}
{'id': 726, 'name': 'drug abuse'}
{'id': 960, 'name': 'homeless person'}
{'id': 1605, 'name': 'new love'}
{'id': 1803, 'name': 'drug addiction'}
{'id': 2635, 'name': 'overdose'}
{'id': 2815, 'name': 'graffiti'}
{'id': 2816, 'name': 'street art'}
{'id': 2818, 'name': 'vernissage'}
{'id': 2819, 'name': 'exhibit'}
{'id': 6054, 'name': 'friendship'}
{'id': 10183, 'name': 'independent film'}
{'id': 14964, 'name': 'drug'}
{'id': 33648, 'name': 'celebration'}

In [145]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4809, dtype: object

In [146]:
movies['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4809, dtype: object

In [147]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [148]:
def convert1(obj):
  l=[]
  c=0
  for i in ast.literal_eval(obj):
    if c!=3:

      l.append(i['name'])
      c+=1
    else:
      break
  return l

In [149]:
convert1('[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}]')

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [150]:
movies['cast']=movies['cast'].apply(convert1)

In [151]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [152]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [153]:
def convert3(obj):
  l=[]
  for i in ast.literal_eval(obj):
    if i['job']=='Director':
      l.append(i['name'])
      break
  return l

In [154]:
movies['crew']=movies['crew'].apply(convert3)

In [155]:
movies.head( )

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [156]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4809, dtype: object

In [157]:
movies['overview'] = movies['overview'].astype(str)
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [158]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [159]:
A=pd.Series(['Action', 'Adventure', 'Fantasy', 'Science Fiction']).apply(lambda x:x.replace(" ",""))
A

0            Action
1         Adventure
2           Fantasy
3    ScienceFiction
dtype: object

In [160]:
movies['genres'][0]

['Action', 'Adventure', 'Fantasy', 'ScienceFiction']

In [161]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [162]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [163]:
new_df=movies[['id','title','tags']]

In [164]:
a=['sci-fi', 'thriller', 'alien']
" ".join(a)

'sci-fi thriller alien'

In [165]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_2921/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [166]:
new_df['tags']=new_df['tags'].apply (lambda x:x.lower())

/tmp/ipykernel_2921/236799254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply (lambda x:x.lower())

In [167]:
import nltk

In [168]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [169]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

In [170]:
new_df['tags']=new_df['tags'].apply(stem)

/tmp/ipykernel_2921/3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [171]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [172]:
vector=cv.fit_transform(new_df['tags']).toarray()

In [173]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [174]:
from sklearn.metrics.pairwise import cosine_similarity

In [175]:
similarity=cosine_similarity(vector)

In [176]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [177]:
def recommend(movie):
  movie_index = new_df[new_df['title']==movie].index[0]
  distances=similarity[movie_index]
  movies_list= sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:10]

  for i in movies_list:

    print(new_df.iloc[i[0]].title)

In [178]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf
Rockaway
Batman v Superman: Dawn of Justice
Synecdoche, New York
Defendor

In [179]:
new_df[new_df['title']=='Batman Begins'].index[0]

np.int64(119)

In [180]:
import pickle

In [181]:
distances=similarity[119]
distances

array([0.0433555 , 0.04583492, 0.09449112, ..., 0.03706247, 0.09545044,
       0.06113544])

In [182]:
new_df['title'][2]

'Spectre'

In [183]:
pickle.dump(new_df.to_dict(),open('movie.pkl','wb'))

In [184]:
pickle.dump(similarity,open('similarity.pkl','wb'))